name: morpheme
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ./core
  splash:
    path: ./features/splash
  auth:
    path: ./features/auth
  home:
    path: ./features/home
  profile:
    path: ./features/profile
  route:
    path: ./features/route
  help:
    path: ./features/help
  main:
    path: ./features/main

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  morpheme_cucumber: ^1.0.2

flutter:
  uses-material-design: true
  assets:
    - integration_test/ndjson/


