name: dependency_manager
description: All dependency package of project here.
version: 0.0.1

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Google Font
  google_fonts: ^6.1.0

  # Navigation
  go_router: ^13.2.0

  # Service Locator
  get_it: ^7.6.7

  # Storage
  flutter_secure_storage: ^9.0.0

  # Component
  skeletonizer: ^1.0.1

  # Utils
  equatable: ^2.0.5
  collection: ^1.18.0

  # Firebase
  firebase_core: 2.25.4
  # firebase_analytics: ^10.8.5
  # firebase_crashlytics: ^3.4.14
  # firebase_remote_config: ^4.3.13

  # Test
  mocktail: ^1.0.3
  bloc_test: ^9.1.6

  #Storage
  shared_preferences: ^2.0.15

  #Component
  shimmer: ^2.0.0
  cached_network_image: ^3.3.0
  cached_memory_image: ^1.5.0

  # Device info
  device_info_plus: ^9.0.3

  # file picker
  file_picker: ^5.2.5
  flutter_image_compress: ^2.1.0

  #image picker
  image_picker: ^0.8.7+4

  # Package info plus
  package_info_plus: ^4.1.0

  # Flutter SVG
  flutter_svg: ^2.0.9

  # Toast
  fluttertoast: ^8.1.2

  # Permission Handler
  permission_handler: ^10.4.5

  # Connectivity
  connectivity_plus: ^6.0.3

  # responsive
  responsive_framework: ^1.1.1

  # path
  path_provider: ^2.1.3
  
  # Maps
  geolocator: 10.0.0
  google_maps_flutter: 2.3.1
  google_maps_utils: 2.0.0+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
