library dependency_manager;

export 'package:collection/collection.dart';
export 'package:equatable/equatable.dart';
export 'package:flutter_secure_storage/flutter_secure_storage.dart';
export 'package:get_it/get_it.dart';
export 'package:go_router/go_router.dart';
export 'package:google_fonts/google_fonts.dart';
export 'package:skeletonizer/skeletonizer.dart';
export 'package:cached_memory_image/cached_memory_image.dart';
export 'package:cached_network_image/cached_network_image.dart';
export 'package:connectivity_plus/connectivity_plus.dart';
export 'package:device_info_plus/device_info_plus.dart';
export 'package:file_picker/file_picker.dart';
export 'package:flutter_image_compress/flutter_image_compress.dart';
export 'package:flutter_svg/flutter_svg.dart';
export 'package:fluttertoast/fluttertoast.dart';
export 'package:image_picker/image_picker.dart';
export 'package:package_info_plus/package_info_plus.dart';
export 'package:permission_handler/permission_handler.dart';
export 'package:responsive_framework/responsive_framework.dart';
export 'package:shared_preferences/shared_preferences.dart';
export 'package:shimmer/shimmer.dart';
export 'package:path_provider/path_provider.dart';
export 'package:geolocator/geolocator.dart' hide ServiceStatus;
export 'package:google_maps_flutter/google_maps_flutter.dart';
export 'package:google_maps_utils/google_maps_utils.dart';
export 'package:uuid/uuid.dart';
